import React, { Component } from 'react';
import "./css/home.css";

class Home extends Component {
  state = {  }
  render() { 
    return ( 
    <div className="homeMainDiv">
    <h1 className="homeH1">Welcome to Organika store</h1>
      <div className="homeDiv">
          <img
            src={"/images/products/img-1.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-2.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-3.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-4.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-5.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-6.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-7.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-8.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-9.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-10.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-11.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-12.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-13.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-14.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/img-15.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-1.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-2.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-3.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-5.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-6.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-7.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-8.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-9.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-10.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-11.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-12.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-13.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-14.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-15.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-16.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-17.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-18.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-19.jpg"}
            className="image"
          ></img>
          <img
            src={"/images/products/product-20.jpg"}
            className="image"
          ></img>
      </div> 
    </div>
    );
  }
}

export default Home;